### PR TITLE
Resurrect (#1)

### PR DESCRIPTION
**Pull request by hartwork**
For #1. Ready for first round of review :smiley:

### CODE REVIEW

**Comment by hartwork** [comment]
> Hey, nice work!

Glad to hear :smile: 

>  I'm getting an error on directory that is symlinked to a path outside of the root.
Could you fix that - maybe make such files not visible so that you'd never
step on this issue? What do you think?

Hiding them would work, or not making them a link. I slightly favour the latter. How about you?

> Also a minor issue with the DEVEVOPS.sh - I don't have path named python2, maybe it would be possible to provide path to python as an optional parameter?

Did it fail? It activates a virtualenv a few lines above and that should have `python2` around, see:
```console
# cd "$(mktemp -d)"

# virtualenv --python=python2 foo
Running virtualenv with interpreter /usr/bin/python2
New python executable in /tmp/tmp.b2vJ7CbM1t/foo/bin/python2
Also creating executable in /tmp/tmp.b2vJ7CbM1t/foo/bin/python
Installing setuptools, pip, wheel...done.

# ls -1 foo/bin/python*
foo/bin/python
foo/bin/python2
foo/bin/python2.7
foo/bin/python-config
```

**Comment by evgenyfadeev** [comment]
I get this:
The path python2 (from --python=python2) does not exist, that's why I thought 
there could be an optional parameter, and a clearer error message.
You can try simulating that with a non-existing python path.

For the symlinks I think the options are 1) disable & hide them completely and 
state that in the readme; 2) allow per configuration setting defaulting to False.
imo it's not useful to show the files but not let them be downloaded/followed.

Nginx has something like that:
http://nginx.org/en/docs/http/ngx_http_core_module.html#disable_symlinks

Oh and lastly - let's rename the DEVEVOPS.sh to RUN_DEMO.sh or something like that.

**Comment by hartwork** [comment]
> The path python2 (from --python=python2) does not exist, that's why I thought
there could be an optional parameter, and a clearer error message.

But you do have Python 2 installed? Would `python2.7` work instead? I'd want to be sure to not end up with Python 3 unnoticed.

>  imo it's not useful to show the files but not let them be downloaded/followed.

In my eyes someone who knows what the directory contains may wonder and be searching why the file is not listed. Not important to me though. I'll go with hiding then.

> Nginx has something like that:
http://nginx.org/en/docs/http/ngx_http_core_module.html#disable_symlinks

That seems to be about following them rather about display, to me. The new code here follows them, as long as things keep inside the virtual root. That felt like both secure and comfort to me.

> Oh and lastly - let's rename the DEVEVOPS.sh to RUN_DEMO.sh or something like that.

Gosh, I really named it `DEVEVOP.sh`. Should have been `DEVELOP.sh` of course. I'll rename it to `RUN_DEMO.sh` if you like.

**Comment by evgenyfadeev** [comment]
Yeah python2.7 works for me, but what if that does not exist for someone else:)...

Re: links - I guess I'm ok with showing the symlink and not allowing to follow if the symlink is a directory and not allow downloading if it's a file...

DEVELOP.sh is fine.

**Comment by evgenyfadeev** [comment]
Done, check this out https://pypi.org/project/django-directory/

**Comment by hartwork** [comment]
Nice, thank you!

**Pull request merged**
