### PR TITLE
Support Django 2

### PR DESCRIPTION
**Pull request by hartwork**
Includes commits from #4 right now, happy to pull that out if #4 gets merged.

### CODE REVIEW

**Comment by evgenyfadeev** [comment]
Hey, when I try to download .pyc file for some reason getting the error below.
Are you able to reproduce this? Cheers!

  File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/socketserver.py", line 647, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/socketserver.py", line 357, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/socketserver.py", line 717, in __init__
    self.handle()
  File "/Users/evgeny/other/django-directory/py3/lib/python3.7/site-packages/Django-2.1.3-py3.7.egg/django/core/servers/basehttp.py", line 154, in handle
    handler.run(self.server.get_app())
  File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/wsgiref/handlers.py", line 144, in run
    self.close()
  File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/wsgiref/simple_server.py", line 35, in close
    self.status.split(' ',1)[0], self.bytes_sent
AttributeError: 'NoneType' object has no attribute 'split'

**Comment by evgenyfadeev** [comment]
yes and then I tried to download some .pyc file via the browser. Other files worked fine.

**Comment by hartwork** [comment]
I see! Please check the latest commit for a fix that works well over here.

**Comment by hartwork** [comment]
Any chance to make that 0.0.3 on PyPI?

**Comment by evgenyfadeev** [comment]
done! thank you!

**Comment by hartwork** [comment]
Nice! Please don't forget about pushing the Git tag as well, I see 0.0.3 missing at https://github.com/ASKBOT/django-directory/releases.

**Pull request merged**
